# Generated by Django 5.1.4 on 2024-12-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='profile_pictures/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.JSONField(default=list)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('max_delivery_time', models.IntegerField(blank=True, null=True)),
                ('min_delivery_time', models.IntegerField(blank=True, null=True)),
                ('user_details', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='OfferDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('revisions', models.IntegerField(blank=True, null=True)),
                ('delivery_time_in_days', models.PositiveIntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('features', models.JSONField()),
                ('offer_type', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20)),
            ],
        ),
    ]
