# Generated by Django 5.1.4 on 2024-12-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('username', models.CharField(default='', max_length=100)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('file', models.ImageField(default='', upload_to='profile_pictures/')),
                ('location', models.CharField(default='', max_length=255)),
                ('tel', models.CharField(default='', max_length=20)),
                ('description', models.TextField(default=' ')),
                ('working_hours', models.CharField(default='', max_length=50)),
                ('type', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
